name: Update Terminal GIF

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

permissions:
  contents: write

jobs:
  update-gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y ffmpeg
          python -m pip install --upgrade pip
          pip install git+https://github.com/x0rzavi/github-readme-terminal.git@main

      - name: Generate terminal GIF
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIFOS_GENERAL_FPS: 13
          GIFOS_GENERAL_LOOP_COUNT: 0
          GIFOS_GENERAL_COLOR_SCHEME: "dracula"

      - name: Commit & Push
        run: |
          git config user.email "osw4l@users.noreply.github.com"
          git config user.name "osw4l"
          git add output.gif
          git commit -m "chore: update terminal gif" || exit 0
          git pull --rebase
          git push
